### ISSUE TITLE
Support Unicode astral characters (including emoji)

### ISSUE THREAD

**Issue by revelt** [nonoroazoro/string-searching#1]
Hello

Consider this example with emoji:

```
const ss = require("string-searching");
const text = "z🦄🐴💘b a🦄🐴💘z a🦄🐴💘b z🦄🐴💘z";
const pattern = "🦄🐴";

// or passing true to search all patterns.
const indexes = ss.boyer_moore(text, pattern, true);
console.log('indexes=' + indexes)
// "indexes=1,10,19,28"
```

However, if you count the indexes, the second occurrence is actually "7", not "10". Just each of preceding emoji were counted as two characters instead of one.

**Comment by nonoroazoro** [comment]
@revelt Thanks for your feedback! You're right that is not supported yet.
<s>I will work on it later, but I'm a little busy right now.
P.S. This project is just for validation. Please use String.prototype.indexOf in production.</s>

It seems that the results of my implementation are same with the official **String.prototype.indexOf (lastIndexOf)** function.
So this is not a bug, but I'm also confused about the official implementation, need further study.

**Comment by revelt** [comment]
hiya! I'll close the ticket as it looks stale. regards, Roy
